SET FOREIGN_KEY_CHECKS=0;
DROP TABLE likes CASCADE;
DROP TABLE scores CASCADE;
DROP TABLE users CASCADE;
DROP TABLE actors CASCADE;
DROP TABLE editors CASCADE;
DROP TABLE directors CASCADE;
DROP TABLE movies CASCADE;
SET FOREIGN_KEY_CHECKS=1;