# Generated by Django 3.2.16 on 2022-11-19 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actors',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('country', models.CharField(blank=True, max_length=30, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('height', models.DecimalField(blank=True, decimal_places=0, max_digits=3, null=True)),
                ('gender', models.CharField(blank=True, max_length=3, null=True)),
            ],
            options={
                'db_table': 'actors',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Directors',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('country', models.CharField(blank=True, max_length=30, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('height', models.DecimalField(blank=True, decimal_places=0, max_digits=3, null=True)),
                ('gender', models.CharField(blank=True, max_length=3, null=True)),
            ],
            options={
                'db_table': 'directors',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Editors',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('country', models.CharField(blank=True, max_length=30, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('height', models.DecimalField(blank=True, decimal_places=0, max_digits=3, null=True)),
                ('gender', models.CharField(blank=True, max_length=3, null=True)),
            ],
            options={
                'db_table': 'editors',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
            ],
            options={
                'db_table': 'likes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('type', models.CharField(blank=True, max_length=20, null=True)),
                ('language', models.CharField(blank=True, max_length=20, null=True)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('total_length', models.IntegerField(blank=True, null=True)),
                ('score', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('score_number', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'movies',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Scores',
            fields=[
                ('user_name', models.OneToOneField(db_column='user_name', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='api.api')),
                ('score', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
            ],
            options={
                'db_table': 'scores',
                'managed': False,
            },
        ),
    ]
